== What is this?

This is the repository for the Spring Cloud Stream Release Train.

It contains projects for maintaining the following components:

* the curated dependencies list of the release train, i.e. `spring-cloud-stream-dependencies`
* the aggregated documentation of the release train;

== Release Train Contents

The release train contains:

* the Spring Cloud Stream core;
* supported binder implementations;

=== Binder implementations

The following binder implementations are currently available:

* *Kafka*  https://github.com/spring-cloud/spring-cloud-stream-binder-kafka
* *RabbitMQ*  https://github.com/spring-cloud/spring-cloud-stream-binder-rabbit

== Contributing

We love contributions.
Follow this https://github.com/spring-cloud/spring-cloud-commons#contributing[link] for more information on how to contribute.

== Code of Conduct
This project adheres to the Contributor Covenant https://github.com/spring-cloud/spring-cloud-stream/blob/master/CODE_OF_CONDUCT.adoc[code of conduct]. By participating, you  are expected to uphold this code. Please report unacceptable behavior to spring-code-of-conduct@pivotal.io.
