<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		 xmlns="http://maven.apache.org/POM/4.0.0"
		 xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<artifactId>spring-cloud-bus-parent</artifactId>
	<version>5.1.0-SNAPSHOT</version>
	<packaging>pom</packaging>

	<name>spring-cloud-bus-parent</name>
	<description>Spring Cloud Bus Parent</description>

	<parent>
		<groupId>org.springframework.cloud</groupId>
		<artifactId>spring-cloud-stream-parent</artifactId>
		<version>5.1.0-SNAPSHOT</version>
	</parent>

	<modules>
		<module>spring-cloud-bus</module>
		<module>spring-cloud-bus-tests</module>
		<module>spring-cloud-starter-bus-amqp</module>
		<module>spring-cloud-starter-bus-kafka</module>
		<module>spring-cloud-starter-bus-stream</module>
	</modules>

	<licenses>
		<license>
			<name>Apache License, Version 2.0</name>
			<url>https://www.apache.org/licenses/LICENSE-2.0</url>
		</license>
	</licenses>
	<developers>
		<developer>
			<id>dsyer</id>
			<name>Dave Syer</name>
			<email>david.syer at broadcom.com</email>
			<organization>Broadcom, Inc.</organization>
			<organizationUrl>https://www.spring.io</organizationUrl>
			<roles>
				<role>lead</role>
			</roles>
		</developer>
		<developer>
			<id>sgibb</id>
			<name>Spencer Gibb</name>
			<email>spencer.gibb at broadcom.com</email>
			<organization>Broadcom, Inc.</organization>
			<organizationUrl>https://www.spring.io</organizationUrl>
			<roles>
				<role>lead</role>
			</roles>
		</developer>
	</developers>
	<properties>
		<spring-cloud-commons.version>5.1.0-SNAPSHOT</spring-cloud-commons.version>
	</properties>

	<dependencyManagement>
		<dependencies>
			<!-- TODO: move commons dependency to stream parent -->
			<dependency>
				<groupId>org.springframework.cloud</groupId>
				<artifactId>spring-cloud-commons-dependencies</artifactId>
				<version>${spring-cloud-commons.version}</version>
				<type>pom</type>
				<scope>import</scope>
			</dependency>
			<dependency>
				<groupId>org.springframework.cloud</groupId>
				<artifactId>spring-cloud-test-support</artifactId>
				<version>${spring-cloud-commons.version}</version>
			</dependency>
			<dependency>
				<groupId>org.springframework.cloud</groupId>
				<artifactId>spring-cloud-stream</artifactId>
				<version>${project.version}</version>
			</dependency>
		</dependencies>
	</dependencyManagement>

</project>
