[[spring-cloud-stream-samples]]
== Sample Applications

There are several samples, all running on the redis transport (so you need redis running locally to test them).


* `source` is a Java config version of the classic "timer" module from Spring XD. It has a "fixedDelay" option (in milliseconds) for the period between emitting messages.

* `sink` is a Java config version of the classic "log" module from Spring XD. It has no options (but some could easily be added), and just logs incoming messages at INFO level.

* `transform` is a simple pass through logging transformer (just logs the incoming message and passes it on).

* `double` is a combination of 2 modules defined locally (a source and a sink, so the whole app is self contained).

* `extended` is a multi-module mashup of `source | transform | transform | sink`, where the modules are defined in the other samples and referred to in this app just as dependencies.

If you run the source and the sink and point them at the same redis instance (e.g. do nothing to get the one on localhost, or the one they are both bound to as a service on Cloud Foundry) then they will form a "stream" and start talking to each other. All the samples have friendly JMX and Actuator endpoints for inspecting what is going on in the system.

