spring:
  application.name: kafka-streams-iq-adv-sample
  cloud:
    stream:
      bindings:
        process-in-0:
          destination: product-events
      kafka.streams:
        binder:
          auto-add-partitions: true
          min-partition-count: 4
          configuration:
            application.server: localhost:8080
            commit.interval.ms: 1000
            state.dir: "${java.io.tmpdir}/kafka-streams_${server.port:0}"
