[[Introduction]]
= Introduction

Sabby Anandan; Marius Bogoevici; Eric Bottard; Mark Fisher; Ilayaperumal Gopinathan; Mark Heckler; Gunnar Hillert; Mark Pollack; Patrick Peralta; Glenn Renfro; Thomas Risberg; Dave Syer; David Turanski; Janne Valkealahti; Benjamin Klein; Vinicius Carvalho; Gary Russell; Oleg Zhurakousky; Jay Bryant; Soby Chacko; Domenico Sibilio

The reference documentation consists of the following sections:

[horizontal]
xref:spring-cloud-stream.adoc#spring-cloud-stream-reference[Overview] :: History, Quick Start, Concepts, Architecture Overview, Binder Abstraction, and Core Features

xref:rabbit/spring-cloud-stream-binder-rabbit.adoc[Rabbit MQ Binder] :: Spring Cloud Stream binder reference for Rabbit MQ
xref:kafka/spring-cloud-stream-binder-kafka.adoc[Apache Kafka Binder] :: Spring Cloud Stream binder reference for Apache Kafka
xref:kafka/kafka-streams.adoc[Apache Kafka Streams Binder] :: Spring Cloud Stream binder reference for Apache Kafka Streams
xref:pulsar/spring-cloud-stream-binder-pulsar.adoc[Apache Pulsar Binder] :: Spring Cloud Stream binder reference for Apache Pulsar
https://github.com/SolaceProducts/solace-spring-cloud/tree/master/solace-spring-cloud-starters/solace-spring-cloud-stream-starter#spring-cloud-stream-binder-for-solace-pubsub[Solace PubSub+ Binder] :: Spring Cloud Stream binder reference for Solace PubSub+ (Partner Maintained)

xref:spring-cloud-stream/overview-error-handling.adoc#spring-cloud-stream-overview-binders[Additional Binders] :: A collection of Partner maintained binder implementations for Spring Cloud Stream (e.g., Azure Event Hubs, Google PubSub, Solace PubSub+)
xref:schema-registry/spring-cloud-stream-schema-registry.adoc[Schema Registry] :: Spring Cloud Stream Schema Registry Reference
https://github.com/spring-cloud/spring-cloud-stream-samples/[Spring Cloud Stream Samples]  :: A curated collection of repeatable Spring Cloud Stream samples to walk through the features

Relevant Links:

[horizontal]
https://cloud.spring.io/spring-cloud-dataflow/[Spring Cloud Data Flow] :: Spring Cloud Data Flow
http://www.enterpriseintegrationpatterns.com/[Enterprise Integration Patterns]  :: Patterns and Best Practices for Enterprise Integration
https://spring.io/projects/spring-integration[Spring Integration]  :: Spring Integration framework

