= Spring Cloud Stream Reference Documentation
Sabby Anandan; Marius Bogoevici; Eric Bottard; Mark Fisher; Ilayaperumal Gopinathan; Mark Heckler; Gunnar Hillert; Mark Pollack; Patrick Peralta; Glenn Renfro; Thomas Risberg; Dave Syer; David Turanski; Janne Valkealahti; Benjamin Klein; Vinicius Carvalho; Gary Russell; Oleg Zhurakousky; Jay Bryant; Soby Chacko; Domenico Sibilio

*{spring-cloud-stream-version}*

:docinfo: shared

The reference documentation consists of the following sections:

[horizontal]
<<spring-cloud-stream.adoc#spring-cloud-stream-reference,Overview>> :: History, Quick Start, Concepts, Architecture Overview, Binder Abstraction, and Core Features
https://docs.spring.io/spring-cloud-stream-binder-rabbit/docs/{spring-cloud-stream-version}/reference/html/index.html[Rabbit MQ Binder] :: Spring Cloud Stream binder reference for Rabbit MQ
https://docs.spring.io/spring-cloud-stream-binder-kafka/docs/{spring-cloud-stream-version}/reference/html/index.html#_apache_kafka_binder[Apache Kafka Binder] :: Spring Cloud Stream binder reference for Apache Kafka
https://docs.spring.io/spring-cloud-stream-binder-kafka/docs/{spring-cloud-stream-version}/reference/html/index.html#_kafka_streams_binder[Apache Kafka Streams Binder] :: Spring Cloud Stream binder reference for Apache Kafka Streams
<<binders.adoc#binders,Additional Binders>> :: A collection of Partner maintained binder implementations for Spring Cloud Stream (e.g., Azure Event Hubs, Google PubSub, Solace PubSub+)
https://github.com/spring-cloud/spring-cloud-stream-samples/[Spring Cloud Stream Samples]  :: A curated collection of repeatable Spring Cloud Stream samples to walk through the features

Relevant Links:

[horizontal]
https://cloud.spring.io/spring-cloud-dataflow/[Spring Cloud Data Flow] :: Spring Cloud Data Flow
http://www.enterpriseintegrationpatterns.com/[Enterprise Integration Patterns]  :: Patterns and Best Practices for Enterprise Integration
https://spring.io/projects/spring-integration[Spring Integration]  :: Spring Integration framework

