version: '3'
services:
  postgres:
    image: postgres:10
    container_name: schema-registry-postgres
    restart: always
    environment:
      POSTGRES_DB: registry
      POSTGRES_USER: root
      POSTGRES_PASSWORD: rootpw
    expose:
      - 5432
    ports:
      - 5432:5432
